on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build
  test: 
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'edge']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - run: ls -lah
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: npm run build
          start: npm run start
          browser: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with: 
          name: cypress-videos
          path: crypress-videos
      - uses: actions/upload-artifact@v3
        if: failure()
        with: 
          name: cypress-screenshots
          path: crypress-screenshots